name: 'acme_field_force'
version: '1.0.0'
profile: 'default'          # <-- Partner Connect usually names this 'default'. Confirm in your env.

model-paths: ["models"]
macro-paths: ["macros"]
test-paths:  ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  acme_field_force:
    staging:
      +materialized: view
      +database: DBT_DEMO_SLV
      facts:
        +schema: FACTS
      dims:
        +schema: DIMS
    intermediate:
      +materialized: view
      +database: DBT_DEMO_SLV
      +schema: FACTS
    marts:
      +materialized: table
      +database: DBT_DEMO_GLD
      +schema: OUTPUT
